[build]
  functions = "./functions"
  publish = "."
  command = "npm install"
  node_version = "18"

[dev]
  framework = "#static"
  targetPort = 8888
  port = 8888
  functionsPort = 9999
  functionsSiteTimeout = 120
  
[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/config.js", "lib/supabase.js"]
  external_node_modules = ["node-fetch", "@supabase/supabase-js"]

[functions.generate-text]
  included_files = ["functions/config.js"]
  memory = 1024
  # Set timeout to 120 seconds for production deployment
  timeout = 120

# Handle API redirects
[[redirects]]
  from = "/api/functions/*"
  to = "/api/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle authentication redirects
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/auth/auth.html"
  status = 200
  force = true
  conditions = {Role = ["!user"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Role = ["user"]}

# Add CORS headers
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Environment variable validation
[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18" } 